### ISSUE TITLE
Using Python 2

### ISSUE THREAD

**Issue by cooperdk** [WikiTeam/wikiteam#433] opened 2022-06-05 22:27 UTC
I am reporting the fact that WikiTeam use Python 2.7 for this set of scripts as a BUG.

The reason why I am doing that is that Python 2.(anything) is no longer supported, no longer updated, no longer used by operating systems, no longer recommended, no longer security patched, - thus no longer very sane to use at all.

Python 2.7 was introduced in July 2010, that is TWELVE years ago. It was **officially killed** and recommended as **do-not-use** two years ago.

This set of scripts need to be ported to Python 3.10+ by sane, capable developers. @elsiehupp does fine work, but she does it without extensive Python knowledge.

**Comment by nemobis** [comment] 2022-06-05 22:38
I don't disagree. Still, this is a duplicate of https://github.com/WikiTeam/wikiteam/issues/395 . Thanks for using/trying/contributing to wikiteam.

**Closed by nemobis** 2022-06-05 22:38 UTC

**Comment by cooperdk** [comment] 2022-06-05 22:50
> I don't disagree. Still, this is a duplicate of #395 . Thanks for using/trying/contributing to wikiteam.

You're right.
But #395 is two years old and as having not been fixed, it would not be illogical to renew it. The scripts should have been ported even long before that report.

@OAHOR suggests using conda to install an environment, but it makes no sense because as I wrote, Python 2.7 is no longer safe to use and @elsiehupp can only do so much.

I am contemplating whether or not to contribute to @elsiehupp if time permits.

**Comment by nemobis** [comment] 2022-06-05 22:59
Please continue any discussion on the other report.
