### ISSUE TITLE
Get just a list of page names 

### ISSUE THREAD

**Issue by AdaptiveAlchemist** [WikiTeam/wikiteam#343] opened 2020-01-07 13:58 UTC
Is it possible to write a script that generates a list of page names and name spaces ? 
The current dumpgenerator.py already does that but Python 2.7 no longer supports pip. 
The api is limited to only 500 page names.

**Comment by nemobis** [comment] 2020-02-07 10:32
dumpgenerator does make a list of titles, so it's not clear to me what the scope of this issue is. If you have issues with running dumpgenerator altogether, then let's be specific about those issues.

**Comment by nemobis** [comment] 2020-02-07 14:52
As for the specific command line option, this is a duplicate of https://github.com/WikiTeam/wikiteam/issues/272 .

**Closed by nemobis** 2020-02-07 14:52 UTC
