### ISSUE TITLE
kitchen module

### ISSUE THREAD

**Issue by Skhsouravhalder** [WikiTeam/wikiteam#427] opened 2022-03-26 02:55 UTC
Please install the kitchen module.
Please install or update the Requests module.

How to solve it. Then I'm use 
import kitchen

And view

import: unable to open X server `' @ error/import.c/ImportImageCommand/348.

**Comment by nemobis** [comment] 2022-03-26 08:59
Il 26/03/22 04:56, Sourav halder ha scritto:
> How to solve it.

You need to use python2.

**Comment by nemobis** [comment] 2022-03-26 09:03
Duplicate of https://github.com/WikiTeam/wikiteam/issues/395

**Closed** 2022-03-26 09:04 UTC
Labels: question
